informalsystems/quint

- .github/workflows/main.yml
We have not been checking CI whether the vscode plugin can be compiled on Mac
and Windows. This change adds that CI check.
> Build vscode plugin in all CI operating systems

- .github/workflows/main.yml
- CONTRIBUTING.md
- Makefile
- examples/tictactoe/tictactoe.qnt
- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/README.md
- vscode/quint-vscode/package.json
This updates the documentation for the extension (with GIFs!) and its developer instructions (`CONTRIBUTING.md` and `Makefile`).
Also, I changed the CI configs so the `vscode` jobs are using the unpublished version of `quint` so we are ensured that changes to `quint` are not breaking the extension.
> Update documentation for the VSCode extension

- quint/src/cliCommands.ts
- quint/src/runtime/compile.ts
- quint/src/types/inferrer.ts
- quint/test/types/inferrer.test.ts
- vscode/quint-vscode/server/src/server.ts
This is a small refactor on the order of parameters for `inferTypes` since they differ from `inferEffects` for no reason. Fixes https://github.com/informalsystems/quint/issues/336.
> Update `inferTypes` parameters to match  `inferEffects`

- CONTRIBUTING.md
- Makefile
I have tried to install the vscode plugin locally and ran into a few problems, since I forgot how it worked after the holidays. After chatting with @bugarela, I've updated `CONTRIBUTING.md` and `Makefile` to hopefully make it easier to install the plugin locally.
> update the makefile and CONTRIBUTING.md

- CHANGELOG.md
- quint/package-lock.json
- quint/src/runtime/impl/compilerImpl.ts
- quint/test/runtime/compile.test.ts
This is a small fix of the REPL behavior on `0^0`. Different languages define `0^0` differently. We follow the behavior of TLC (and the usual definition of `0^0` in math).
> fix REPL for `0^0`

- quint/package.json
I had a false positive while testing this library and only now realize it is actually missing a flag. It is not trivial to test this in CI, as our test suite runs on top of the `ts` source files and not `dist` iiuc.
PS: I'm using the `copyfiles` lib instead of `cp` to provide support to all OS.
> Add missing flag to `copyfiles`

- CHANGELOG.md
- quint/package-lock.json
- quint/package.json
- Fixed REPL output for maps (#497)
- REPL reporting a runtime error on `0^0` (#492)
- Improved how documentation is produced for VSCode compatibility (#485)
- Enable access to builtin documentation parsed from `builtin.qnt` (#485)
- The effect and mode checkers no longer complain about runs (#505)
- Fixed missing lodash dependency (#484)
- A tutorial on integers (#484)
> Release 0.5.1

- tutorials/README.md
The current link returns a 404, this is a trivial fix.
> Fix link to hello world tutorial

- doc/lang.md
This PR introduces warnings in the language manual, so people should not use unimplemented features, which we thought were too advanced for the beginners.
> add warning for the features under construction

- CHANGELOG.md
- doc/lang.md
- examples/ERC20/erc20.qnt
- quint/src/builtin.qnt
- quint/src/definitionsCollector.ts
- quint/src/effects/builtinSignatures.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/src/types/builtinSignatures.ts
- quint/test/runtime/compile.test.ts
Closes #543. Introduce the operator `fail` that flips the result of a run from success to failure and vice versa. This operator is useful for writing tests that are expected to fail.
> add the operator 'fail'

- .github/pull_request_template.md
- doc/builtin.md
I noticed we forgot to update `builtin.md` in https://github.com/informalsystems/quint/pull/552, which was actually a hard thing to remember anyway. So I'm doing that and also adding an entry to our PR template to help us remember to do that in the future. Eventually we can automate this, of course.
> Regenerate docs and add that to PR checklist

- CHANGELOG.md
- doc/lang.md
Closes #542. `assert` is now an action operator, not a run operator. I did not have to do much except moving the description in the manual.
As far as I understand, the mode checker does not enforce modes for some operators, e.g., I could do the following in REPL, which I expected the mode checker to complain about:
```
pure def a = assert(false)
```
> Promote `assert` to be an action operator 

- CHANGELOG.md
- examples/counters.qnt
- quint/cli-tests.md
- quint/io-cli-tests.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/repl.ts
- quint/test/repl.test.ts
I have added a few productivity tricks to running REPL for loading files:
- CLI:
- `quint -r filename.qnt` loads `filename.qnt` right after the start
- `quint -r filename.qnt::myModule` loads `filename.qnt` right after the start and imports `myModule`
- REPL:
- `.load filename.qnt myModule` loads `filename.qnt` and imports `myModule` (I believe this should be replaced with an import from a file in the future)
- `.reload` clears the history, loads the previously loaded file and imports `myModule` (if it was previously imported).
These hacks should help us in automation of follow-up tutorials.
> add a few productivity hacks to repl

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
- Support for "Go to definition" (#546).
> Release VSCode extension v0.1.2

- quint/src/repl.ts
removed the chalk.black so that the terminal would use the default foreground
resolves #574
> Fix: REPL Output Color In Dark Terminal

- CHANGELOG.md
- quint/src/runtime/impl/compilerImpl.ts
Closes #444. Add a less confusing error messaging for the example:
```
val x = 1
x' = 2
```
It's actually surprising that this code made it to REPL without an error by the mode checker. I guess, this is one of the known issues, @bugarela?
> add better error handling

- CHANGELOG.md
- quint/package-lock.json
- quint/package.json
- Change the grammar to support multiple modules (#547)
- Change static analysis to support multiple modules (#559)
- Add an example that specifies the Solidity Coin contract (#576)
- A work-in-progress example on Solidity's Simple Auction (#573)
- Parse `100_000_000` and `0xabcd`, `0xAB_CD` as integers (#580)
- The parser complains about junk in the end of file (#603)
- Fix a confusing error message in assignments (#606)
- REPL compiles unsupported operators and issues runtime errors (#604)
> Release v0.5.5

- editor-plugins/emacs/quint-mode.el
- editor-plugins/highlight.js/quint.js
- editor-plugins/highlight.js/testHighlightJs.html
- editor-plugins/vim/quint.vim
- vscode/quint-vscode/syntaxes/quint.tmLanguage.json
Closes #444 and many issues with syntax highlighting in vscode, vim, and emacs. Actually, we had a lot of keywords for operators that do not require any special treatment, they are just standard names.
On top of that, I have added a simple syntax schema for highlight.js with the intention to use it in the tutorials. You can see how it is supposed to work in `editor-plugins/highlight.js/testHighlightJs.html`. It needs integration in the tutorials though.
> fix syntax highlighting

- editor-plugins/emacs/quint-mode.el
Some commas found there way into the quoted list. Not sure when these
slipped in, but no time recently!
> Remove errant commas from the emacs quint-mode

- CHANGELOG.md
- README.md
- doc/quint.md
- examples/language-features/counters.qnt
- quint/io-cli-tests.md
- quint/package-lock.json
- quint/package.json
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/repl.ts
- quint/src/runtime/compile.ts
- quint/src/runtime/testing.ts
- quint/test/runtime/compile.test.ts
Closes #628.
This PR introduces the command `test` that mimics the behavior of a unit-testing framework, e.g., of mocha. This command should let us integrate basic tests for protocols in the CI.
> Introduce the testing framework

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/runtime/compile.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/test/repl.test.ts
- quint/test/runtime/compile.test.ts
Closes #648. Since REPL is using multiple top-level modules now, we have to be careful about mapping variables from different modules to different modules. In this PR, all variable names are prefixed with the module name. This fixes the bug, but it slightly changes the behavior of `_lastTrace`, which now contains fully qualified names instead of local names. Since we have some rework planned for `_lastTrace` in any case, I will revisit this behavior of `_lastTrace` later.
> Fix a bug introduced during REPL refactoring

- CHANGELOG.md
- quint/package-lock.json
- quint/package.json
- command `test` to run unit tests (#634)
- option `--with-lookup` of the command `parse` (#639)
- `docs` subcommand now outputs generated docs to stdout (#617)
- Mode errors are better explained and include a fix suggestion (#619)
- Typechecking now reports errors when instance overrides are not compatible with
the original definition (#622)
- REPL does not support nested modules any longer (#621)
- REPL avoid name clashes in different modules (#621)
- REPL session is now a proper Quint file (#621)
- A regression in REPL caused by multiple modules (#650)
- the [Prisoners puzzle](./examples/puzzles/prisoners) (#634)
> Release v0.6.0

- CONTRIBUTING.md
- quint/scripts/prepare-release.sh
- quint/scripts/release.sh
- vscode/quint-vscode/scripts/prepare-release.sh
Closes #655 
Expands and tweaks the existing VSCode release prep script to make the process
of preparing the release commit fully automated. It basically just follows the
example from other parts of #470.
The script was used to prepare #654
> Finish off automation of VSCode release prep

- .github/workflows/main.yml
- .gitignore
- Makefile
- quint/README.md
- quint/apalache-tests.md
- quint/package.json
Closes #635
Adds basic integration tests with Apalache, to ensure we can catch any breakage
in our integration with the model checker.
The approach here is dead simple:
We add a phony make target that will always fetch the latest Apalache release,
then a suite for txm tests that will parse specs with quint and then feed the
JSON IR to Apalache.
As per our discussions, ultimately this will be supplanted with a quint
subcommand that routes invocations thru apalache's server-mode. For now, we just
want to catch breakage.
> Add integration tests with Apalache

- CHANGELOG.md
- quint/src/effects/inferrer.ts
- quint/src/effects/substitutions.ts
- quint/test/effects/inferrer.test.ts
Closes #662. In operator application, instead of applying new substitutions to all previously inferred effects, apply them only to effects from the application itself (parameters and result). In order for this to work, we need to compose these new substitutions with the previously known substitutions in a way where the "older" variables are binded to the new ones, as the new ones wouldn't occur elsewhere.
This reduces typechecking of `ics23` to 7 seconds (from over 70s in `main`).
I realize that accumulating all substitutions in `this.substitutions` is also reckless, but this is not considerably affecting performance at this point and it is not trivial to figure out the scope to which we should propagate those.
> Fix effect checker performance killer

- quint/src/effects/EffectVisitor.ts
- quint/src/effects/MultipleUpdatesChecker.ts
- quint/src/effects/ToEffectVisitor.ts
- quint/src/effects/base.ts
- quint/src/effects/builtinSignatures.ts
- quint/src/effects/inferrer.ts
- quint/src/effects/modeChecker.ts
- quint/src/effects/printing.ts
- quint/src/effects/simplification.ts
- quint/src/effects/substitutions.ts
- quint/src/generated/Effect.g4
- quint/src/generated/Effect.interp
- quint/src/generated/EffectListener.ts
- quint/src/generated/EffectParser.ts
- quint/src/generated/EffectVisitor.ts
- quint/test/effects/EffectVisitor.test.ts
- quint/test/effects/base.test.ts
- quint/test/effects/inferrer.test.ts
- quint/test/effects/parser.test.ts
- quint/test/effects/substitutions.test.ts
This fixes #668 by renaming `Variables` to `Entity`, and the kind `'quantified'` to `'variable'` (plus some consequential renaming from that).
> Renaming across effect system

- CHANGELOG.md
- quint/src/importResolver.ts
- quint/src/quintError.ts
- quint/test/importResolver.test.ts
Closes #523 by preventing a module to import or instance itself. I believe the remaining problems of the issue were already addressed by removing nested modules :smile:
> Prevent self imports and instances

- CHANGELOG.md
- quint/package-lock.json
- quint/package.json
- Inferred effects are now properly quantified (#658)
- Nested modules are no longer supported (#674)
- Modes for nested definitions are now properly checked (#661)
- All basic operators can now be used with temporal formulas (#646)
- Effect checking performance for large specs is massively improved (#669)
- A module can no longer import or instance itself (#676)
> Release v0.7.0

- vscode/quint-vscode/CHANGELOG.md
This is just to explain what occasions the release, so we don't have an
empty changelog.
> Update  changelog for pending VSCode release

- doc/builtin.md
- quint/src/builtin.qnt
The API docs for `put(m, k, v)` currently state
```
If `k` is present in `m`, this operator has undefined behavior.
```
whereas the language doc claims
https://github.com/informalsystems/quint/blob/d8c1150c9c8721565b3fb006d255918906e9a574/doc/lang.md?plain=1#L1238-L1240
(which would both extend or replace the `k -> v` binding).
@konnov confirmed that the latter is the intended semantics.
> Update built-in docs for `put`

- CHANGELOG.md
- examples/language-features/nondet.qnt
- quint/cli-tests.md
- quint/io-cli-tests.md
- quint/src/runtime/impl/compilerImpl.ts
Closes #710. Closes #545. Finally, I have understood the cause of the heisenbugs in the simulator. `nondet x = oneOf(S); A` behaved too random, as it could produce different values for `x` in a single evaluation of `A`. Fixed it by caching the non-deterministic value in a single evaluation of `A`.
It's actually a critical bugfix. We should cut a new release once it is merged.
> fix too much non-determinism in nondet

- examples/README.md
- examples/solidity/icse23-fig7/README.md
- examples/solidity/icse23-fig7/lottery.qnt
- quint/cli-tests.md
This is a yet another example of how we could use Quint to specify non-trivial behavior of smart contracts. The interesting thing about this example is that it is one of the highlights from the paper by [Zhang, Zhuo, Xu, Lin](https://github.com/ZhangZhuoSJTU/Web3Bugs) at ICSE'23. This example is in the category of contracts that cannot be reasoned automatically by static analysis tools. This is not really surprising, as the security property requires us to specify the behavior of the contract and the behavior of the Solidity mempool.
I was able to specify the property as a state invariant and reproduce it with a test in Quint. However, the random simulator did not find the violation after 10 min. Seems like a good call for Apalache (and more advanced fuzzing).
Also, this example screams: …
> Add a lottery example

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
- Go to definition now works for parameters (#711)
- Go to definition now works for type aliases (#726)
> VSCode Release v0.2.1

- quint/README.md
Hello :octocat:
Our normal use case requires the global flag for npm, see https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation#which-to-choose
> Add global flag to README command

- quint/README.md
We can't run quint with versions of node prior to 14 due to [this](https://stackoverflow.com/questions/74590641/unexpected-token-when-trying-to-run-npm-run-dev). I have tested version 14 and it works. I have not tested previous versions because they are not easily available for my OS, but we got a report that it in fact breaks on node 12.
> Add node dependency

- CHANGELOG.md
- doc/quint.md
- quint/io-cli-tests.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/runtime/testing.ts
- quint/src/verbosity.ts
Contributes to #754. This PR implements `--verbosity=3` for `test`, similar to how it was done for `run`.
> Add verbose execution output to `test`

- CHANGELOG.md
- doc/quint.md
- examples/cosmos/ics23/ics23.qnt
- quint/io-cli-tests.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/repl.ts
- quint/src/runtime/compile.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/src/simulation.ts
- quint/src/verbosity.ts
- quint/test/repl.test.ts
- quint/test/runtime/compile.test.ts
Closes #754. Closes #762. This PR finishes the work on detailed output for operator evaluation. As in case of `run` and `test`, this output is enabled with `--verbosity=3`. Additionally, one can enable it with `.verbosity=3` directly in REPL.
I've also found the case when the action call was not tracked, namely, the case of nullary actions like `init` or `step`. Fixed that. As a result, the detailed output is a bit more verbose than before.
Also, I've renamed all operators like `__test` and `_lastTrace` to `q::test` and `q::lastTrace`. Let's use the namespace `q` for the operators internal to Quint.
> Showing execution details in REPL

- CHANGELOG.md
- editor-plugins/vim/quint.vim
This one-liner fixes vim highlighting
> fix highlighting for numbers in vim

- CHANGELOG.md
- quint/package-lock.json
- quint/package.json
- detailed run output on `run --verbosity=3` (#748)
- detailed run output on `test --verbosity=3` (#755)
- detailed run output in REPL on `.verbosity=3` (#764)
- remove `foldr` (#760)
- Effects no longer break when applying constant operators (#759)
- Number highlighting in vim (#765)
> Release v0.9.0

- CHANGELOG.md
- quint/cli-tests.md
- quint/io-cli-tests.md
- quint/src/cliCommands.ts
Closes #772
We have a uniform mechanism for reporting errors (along with exit codes) for
failed executions, but the `test` subcommand wasn't using it, so it was exiting
with a `0` and without reporting on stderr. 
This change makes it so that `test` produces a non-zero exit code on failures.
Note that this has also uncovered a failing test.
> Fix test command error reporting

- examples/language-features/instances.qnt
- quint/io-cli-tests.md
- quint/src/flattening.ts
- quint/test/flatenning.test.ts
We all noticed some weird things breaking on the compiler last week, and that's because there were many scenarios (mostly involving `export`) where the flattening procedure was not doing the right thing. This fixes a bunch of those and introduces more tests, including integration tests for the `language-feature` examples for imports and instances (which were only being parsed and typechecked until now).
> Extend flattening to support `export`

- CHANGELOG.md
- quint/src/effects/inferrer.ts
- quint/src/effects/modeChecker.ts
- quint/test/effects/inferrer.test.ts
This is a quick fix to #810. We were not properly checking for lambdas returning operator, which is not allowed. The mode checker would throw:
```
Error: Unexpected arrow found in operator result: (e0) => (e1) => e1
at modeForEffect (/home/gabriela/projects/quint/quint/dist/src/effects/modeChecker.js:142:23)
at ModeChecker.exitOpDef (/home/gabriela/projects/quint/quint/dist/src/effects/modeChecker.js:51:37)
```
Now we report it properly, so the error looks like this:
```
/home/gabriela/projects/quint/examples/test.qnt:3:26 - error: [QNT000] Result cannot be an opperator
Inferring effect for f
3:   pure def myOp = (_) => f
^
error: typechecking failed
```
> Report error when lambda returns an operator

- CHANGELOG.md
- quint/src/repl.ts
- quint/src/rng.ts
- quint/test/repl.test.ts
This PR implements the command `.seed` that sets the random seed right in REPL.
Here is an example:
> set the seed in REPL

- CHANGELOG.md
- quint/src/cliCommands.ts
A one-line fix for the issue that I somehow introduced in `run`: It stopped showing compile errors. 
I wanted to add a test for it, but then realized that it was hitting a rare case when the spec was parsed, type checked, resolved, but then the compile phase in the simulator failed. We should add some tests for this behavior in the future.
> fix error output

- CHANGELOG.md
- quint/src/runtime/impl/compilerImpl.ts
Closes #807. This PR adds caching of top-level `pure val`, similar to caching of nested `pure val`. There is not much we can test here.
> cache pure val

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/cliCommands.ts
- quint/src/runtime/testing.ts
- quint/testFixture/_1040compileError.qnt
Closes #828. This PR fixes the problem of compilation errors not being shown by `quint test`.
> handle compilation errors that occur in `quint test`

- CHANGELOG.md
- quint/cli-tests.md
- quint/src/runtime/impl/compilerImpl.ts
- quint/testFixture/bug843pureValCache.qnt
Closes #843. Fixed the bug with spurious caching of nested `pure val`s.
> fix the bug 843

- quint/src/flattening.ts
- quint/src/runtime/compile.ts
- quint/src/types/base.ts
- quint/src/types/constraintGenerator.ts
- quint/test/flatenning.test.ts
This closes #846 by adding a type map update every time we generate a new id for an expression, the same way we did for the source map. Effects are not handled yet since they don't even make it to this step of compilation (the map is not available, so there's nothing to update).
> Update type maps at flattening with new generated ids

- examples/cosmos/ics20/bank.qnt
- examples/cosmos/ics20/base.qnt
- examples/cosmos/ics20/denomTrace.qnt
- examples/cosmos/ics20/ics20.qnt
- quint/cli-tests.md
This adds a first complete version of the ICS20 spec, integrating with the existing `bank.qnt` and `denomTrace.qnt` specs. I've also extracted some common definitions to `base.qnt`.
The commit history is a mess because I'm afraid of rebasing this (since I've started working on top of two existing branches), but the diff is correct.
I'll do some other iterations on this spec, adding invariants and some non-happy-path examples.
Closes https://github.com/informalsystems/apalache-team-services/issues/4
> ICS20 spec integrating `bank` and `denomTrace`

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/server/src/documentSymbols.ts
- vscode/quint-vscode/server/src/server.ts
I needed a little side project, and since I keep getting lost in the ICS-20 spec:
this adds an LSP endpoint to populate VSCode's outline view
Not sure if there's a meaningful way to test this.
> Add LSP handler for `textDocument/documentSymbol`

- quint/.eslintrc.json
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/test/cli.test.ts
Closes #872
Took out parts from
https://github.com/informalsystems/quint/commit/ca7281dfe2ac435ed494bbe271db429fc4495baf
This frees us up to use async operations within the subcommands, when
needed.
> Make CLI commands async

- examples/cosmos/ics20/bank.qnt
- examples/cosmos/ics20/base.qnt
- examples/cosmos/ics20/ics20.qnt
Towards https://github.com/informalsystems/apalache-team-services/issues/8
Handle failed acknowledgements in the ICS-20 spec:
- Add `refundTokens`, `onAcknowledgePacket`, `onTimeoutPacket` definitions from ICS 20
- Update the `receivePacket` action to produce an acknowledgement
- Add a `receiveAck` action to receive an in-flight acknowledgement on the source chain
- Add a test provoking a failed acknowledgement
This PR is interspersed with various refactorings, but they are isolated to principled separate commits.
Since this has grown a lot, I will add the timeout action + test in a separate PR.
> Extend ICS-20 spec with failed acks

- examples/cosmos/ics20/ics20.qnt
Closes https://github.com/informalsystems/apalache-team-services/issues/11 by adding a concrete test based on the test in the go implementation. Does not add a parametrization on top of this yet.
The comments on the go test are outdated (seems like they updated the test and forgot about the comments). I'll open a PR fixing that. For now, if you are going to review this while looking at the code, I suggest ignoring their comments since that can be very confusing.
Perhaps is a good idea o hold on reviewing this until I have the comments fixed there.
**UPDATE**: here's the test with updated comments and other improvements
https://github.com/cosmos/ibc-go/blob/ce6ee2661f068a36fc112b29aa81b6a9c79685e8/modules/apps/transfer/transfer_test.go#L46
> ICS20 test based on `transfer_test.go`

- editor-plugins/vim/quint.vim
Two minor contributions with this PR, both of them in the syntax file provided for Vim text editor. Each commit refers to one proposed change:
1. The `autogroup` setup can be much simple, 1 line instead of 4 on `~/.vimrc`. Also, using `runtime` is more adequate considering arbitrary setups. In any case, the previous version didn't work, as `~/vim` was used instead of the default `~/.vim`.
2. Syntax highlighting can be configured per file, using `modeline`. Namely, by adding `// vim: syntax=quint` to the end of a file, we instruct Vim to load the Quint syntax for the file. This could be a good practice for published Quint files.
> editor-plugins/vim: improve examples of how to adopt the provided syntax highlighting

- examples/cosmos/ics20/README.md
Closes https://github.com/informalsystems/apalache-team-services/issues/13
Extend the ICS 20 README to reflect the current state of the spec.
This has become more of a tutorial-style text, but I think this fits well with our IBC outreach objective.
> Update ICS 20 readme

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/server/src/server.ts
I introduced a bad bug when optimizing the plugin. The static analysis result was overwriting the parsing results. This ensures the diagnostics are accumulated properly between the two phases.
> Ensure parsing diagnostics are not overwritten

- quint/src/itf.ts
- quint/test/itf.test.ts
For #888, we'll need to support converting ITF into `QuintEx`. Having a
type to specify the right shape for the ITF will make the conversion a
nobrainer, and help ease any other manipulation of ITF data in the
future.
This also adds some minor cleanup to the ITF representation to make it
more faithful: namely, number are numbers, and bitings are encoded as
strings.
-------
> Introduce an ItfTrace type

- quint/src/itf.ts
- quint/test/itf.test.ts
- quint/test/util.ts
Adds a function to convert ITF traces into trades represented as an array of
`QuintEx`s.
Required for #888
> Add ofItf function

- CHANGELOG.md
- README.md
- examples/verification/README.md
- examples/verification/defaultOpNames.qnt
- quint/apalache-tests.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/quintVerifier.ts
- quint/testFixture/apalache/README.md
- quint/testFixture/apalache/deadlock.qnt
- quint/testFixture/apalache/violateOnFive.qnt
Towards #888
This adds handling for variant violations and deadlocked errors reported by Apalache.
There are also tests added for CLI configuration via `--step` and `--init` flags.
> Print counterexamples on variant violations and deadlocks

- CHANGELOG.md
- quint/cli-tests.md
- quint/src/runtime/trace.ts
This PR fixes a bug in reporting by `quint run`, which I have introduced before the presentation in a rush in #890. The simulator was quickly finding a violation but it was reporting the trace as no-violation. Also, added a test to check that the found trace is reported properly.
This is a critical fix actually. Can we cut a new release after this is merged?
> fix trace selection in the simulator

- examples/solidity/ERC20/README.md
This is coming out of nowhere, sorry. Was just browsing the documentation and found this broken link.
This PR is just a small and quick fix for that.
> fix ERC20 broken link

- quint/src/IRprinting.ts
- quint/test/IRVisitor.test.ts
- quint/test/IRprinting.test.ts
- quint/test/effects/inferrer.test.ts
- quint/test/flatenning.test.ts
Our grammar and parser require lambda parameters to be wrapped in parenthesis, and the current pretty printing is not including parenthesis around parameters. This PR fixes that
> Fix pretty printing of lambdas

- README.md
- examples/classic/sequential/BinSearch/BinSearch10.qnt
- quint/apalache-tests.md
- quint/src/cliCommands.ts
- quint/src/flattening.ts
Flatten modules in `quint verify`, to support imports and const instantiation.
Closes #936
> Support imports & module instances in `quint verify`

- .gitattributes
Add GH linguist override to treat `.qnt` files as Bluespec in `.gitattributes`.
This should work for all files with `.qnt` extension, similar to a `// -*- mode: Bluespec; -*-` mode line in each file.
For details, see https://github.com/github-linguist/linguist/blob/master/docs/overrides.md
> Treat .qnt files as bluespec

- CHANGELOG.md
- examples/cosmos/ics20/denomTrace.qnt
- quint/src/effects/modeChecker.ts
- quint/test/effects/modeChecker.test.ts
It's a Friday miracle, I could finally fix #808 :tada: 
I thought unpacking was doing something wrong, then I though arrow effect simplification was doing something wrong... but in the end, it was not even an effect inference issue, but a problem in mode checking!
For mode checking arrow effects, we want to see if there are entities in the result that are not present on the parameters. When mode checking an effect like `(Read[v0, v1] & Temporal[v2, v3]) => Read[v0, v1] & Temporal[v2, v3]`, we were not properly handling unions (i.e. `[v0, v1]`), so we were saying that `v2 != [v2, v3]` and `v3 != [v2, v3]`, therefore `v2` and `v3` were new temporal entities and the overall mode had to be temporal, which of course is wrong.
So I fixed the mode checker to properly recurse …
> Ensure entities are flattened in mode checker

- quint/apalache-dist-tests.md
- quint/src/quintVerifier.ts
Fix an issue where `quint verify` crashes with `ERR_INVALID_ARG_TYPE` when `APALACHE_DIST` is not set.
Closes #905
> Avoid `ERR_INVALID_ARG_TYPE` if `APALACHE_DIST` is not set

- CHANGELOG.md
- quint/src/effects/inferrer.ts
- quint/src/types/constraintGenerator.ts
- quint/test/types/inferrer.test.ts
This fixes #966 by improving how quantification is done in the type checker. We now keep a stack of free type names and use the set of free names in the current lambda scope to decide which variables to quantify.
In a follow-up, I'll check if we need to do the same for effects.
> Fix type quantification

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
- Fix pretty-printing bug where types for tuples didn't have parenthesis around them (#969).
> VSCode Release v0.5.2

- quint/test/repl.test.ts
Closes #980. This PR adds a regression test that should fail if the random seed is not saved between two evaluations in REPL.
> add a regression test for saving seed in repl

- README.md
- examples/.scripts/README-text.md
- examples/README.md
- quint/src/flattening.ts
- quint/src/types/aliasInliner.ts
- quint/src/types/constraintGenerator.ts
- quint/test/flatenning.test.ts
- quint/test/types/aliasInliner.test.ts
This is part two of two and closes #976.
This PR introduces inlining of type aliases in type maps, so when we try to get the inferred type for a definition/expression, the type will not contain any aliases (unless the alias is an uninterpreted type).
I had to change a bit our test framework for flattening in order to test this, and while doing that, I stumbled upon a problem where we weren't adding types for `assume` expressions to the type map. That was easy enough to fix.
> Inline type aliases in the type map

- examples/spells/basicSpells.qnt
This is a simple PR that adds `abs` to basic spells (I found myself needing it a couple of times).
My assumption is that this (since it is not a new functionality) does not need any update to CHANGELOG, let me know if I am wrong about that.
> Added a spell for the absolute value

- .github/pull_request_template.md
@Kukovec raised the problem that CI can unexpectedly fail if the PR author doesn't know about some auto-generated files requiring updates. This adds a comment to the PR template to act as a heads up that it can happen, and also explains how to prevent it or act upon it.
I'm not super confident about the text, so suggestions are welcome!
> PR template comment on CI update checks

- examples/classic/distributed/ClockSync/clockSync3.qnt
Remove the unused state variable `adj` from `clockSync3.qnt`.
This corresponds to unimplemented functionality in the [TLA+ template](https://github.com/informalsystems/tla-apalache-workshop/blob/main/examples/clock-sync/ClockSync3.tla) where this was translated from.
The variable was declared and initialized, but overlooked in the other actions.
@bugarela Shouldn't the effects checker notice a missing assignment?
It was only flagged in Apalache's transition finder.
> Remove unused state var in `clockSync3.qnt`

- CHANGELOG.md
- quint/src/names/definitionsByName.ts
- quint/src/names/definitionsScanner.ts
- quint/src/names/nameResolver.ts
- quint/src/names/scoping.ts
Towards #994 
This is a small addition that improves performance significantly. The problem here is a bit more structural in the name resolution step, which also doesn't have a good interface to enable incremental resolution at the moment.
I will address the structural problems (probably next week), but I decided to propose this small change right now as I had already implemented it and the performance improvement can be useful for our users (specially Manu, whose spec was taking ~60s to load and now takes ~25s).
> Cache results of `scopesForId`

- Makefile
- examples/.scripts/run-examples.sh
Two small improvements/fixes to the examples tooling:
- Make target for `examples/README.md` phony, so that it can be run even when the example sources don't change (e.g., to test Apalache modifications)
- Use `APALACHE_DIST` in `run-examples.sh` if already set, to allow reusing a local Apalache repo
> Small improvements/fixes to the examples tooling

- .github/workflows/main.yml
GNU parallel is not available on the macOS CI runner.
Install it through homebrew.
This is more of a workaround, we should find a better way of handling dev dependencies. /cc @shonfeder 
Closes #1004
> Install GNU parallel on macOS runner

- examples/README.md
Update the examples table to reflect recent updates in Apalache.
The changes in Apalache [v0.40.5](https://github.com/informalsystems/apalache/pull/2624) and [v0.40.6](https://github.com/informalsystems/apalache/pull/2630) in combination enable `clockSync3`.
I'm opening the PR for review now; CI will pass when https://github.com/informalsystems/apalache/pull/2630 is merged and the release is published.
> Update examples table

- examples/.scripts/run-example.sh
- examples/README.md
- examples/classic/distributed/LamportMutex/LamportMutex.qnt
Instantiate parameterized module `LamportMutex` to let it go through `quint test` and `quint verify`.
I chose the same parameters as in Apalache tests: https://github.com/informalsystems/apalache/blob/191bca02b14572e5b13f3dbdc8b490d4d89be50b/test/tla/MC_LamportMutexTyped.tla
This also updates the example runner to consider (hardcoded) `--main`/`--init`/`--step` that differ from the file name. This is a quick fix for now, I will revisit this with a better solution when we have a majority of the examples working.
> Add instantiating module to `LamportMutex`

- examples/classic/distributed/Paxos/Paxos.qnt
Update `Paxos` example:
* Replace the inline mock `Voting` module with a proper file import
* Add an instance for model checking (same parameters as in Apalache tests)
(This still doesn't pass through Apalache, because the spec uses discriminated unions, which [aren't implemented as of now](#539))
> Update Paxos example

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/server/src/documentSymbols.ts
Assign more granular VSCode `SymbolKind`s to `QuintOpDef`s in LSP.
This results in nicer icons in the VSCode outline view:
I particularly like having separate icons for actions and runs, to find them quickly 🤓
> Better (more) icons in VSCode outline

- CHANGELOG.md
- doc/builtin.md
- doc/lang.md
- quint/src/builtin.qnt
- quint/src/effects/builtinSignatures.ts
- quint/src/names/base.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/src/types/builtinSignatures.ts
- quint/test/runtime/compile.test.ts
Closes #848. A bit of cleanup work. This PR simply removes `repeated`, as was planned in #848.
> remove 'repeated'

- CHANGELOG.md
- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/syntaxes/quint.tmLanguage.json
Closes #524. Fixes highlighting of identifiers that contains numbers, e.g., `Foo123`.
> fix the order of identifiers and numbers in vscode highlighting

- examples/.scripts/README-text.md
- examples/README.md
- examples/cosmwasm/zero-to-hero/vote.qnt
This adds an example spec of a CosmWasm smart contract.
The example follows the tutorial at: https://github.com/Callum-A/cosmwasm-zero-to-hero
The spec is still missing [the last part of the tutorial](https://github.com/Callum-A/cosmwasm-zero-to-hero/tree/main/14%20-%20Query%20Tests), and more Quint-specific parts (state machine, invariants, ...), but I wanted to merge this as intermediate state.
I'm putting it into a new `cosmwasm` directory for visibility – the `cosmos` directory is rather low level.
Towards #52
> Add cosmwasm example

- examples/cosmwasm/zero-to-hero/vote.qnt
Update the CosmWasm `from-zero-to-hero` example with a state machine + invariants.
Closes https://github.com/informalsystems/apalache-internal/issues/52
> Extend CosmWasm example with state machine + invariants

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/quintError.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/testFixture/_1041compileConst.qnt
Closes #1048. The compiler produces a more meaningful message on a constant.
> produce a friendlier error on const

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/cliCommands.ts
- quint/src/repl.ts
- quint/test/repl.test.ts
This is a quality of life improvement in REPL. I've noticed that I would usually like to see an execution trace when a test is failing in REPL, when setting `.verbosity` to 3-4. This is what this PR does.
> Output the execution stack on undefined values in REPL

- CHANGELOG.md
- quint/src/errorReporter.ts
Closes #1061. It happened several times that the error formatter was throwing a new exception, instead of explaining the error. In the long run, we should carefully proof-read `formatError`. This PR wraps `formatError` code in try/catch, so `quint test` does not simply crash in error formatting, but print the stack trace and continues.
I believe that this should be the tool behavior for the non-critical logic.
> wrap formatError

- examples/.scripts/run-example.sh
- examples/.scripts/run-examples.sh
- examples/README.md
- examples/cosmos/lightclient/Lightclient.qnt
Update example runner + dashboard for lightclient spec:
* Mark included specs Blockchain.qnt and LCVerificationApi.qnt as N/A (they are parameterized and cannot be run)
* Supply `--init` and `--next` for Lightclient.qnt
* Add an instance module[^1] to Lightclient.qnt, in support of `test` and `verify`, and add it as `--main`
ℹ️ &nbsp; `Lightclient` does not pass test and verify yet; most likely this is addressed by @bugarela's current flattener workstream.
[^1]: This just adds the "smallest" of [the TLA+ `MC_` modules](https://github.com/cometbft/cometbft/tree/c3acdb866f885e94dcd0e1ef8ecce53ff689216c/spec/light-client/verification); adding the remaining ones is tracked in #1016)
> Update example runner + dashboard for lightclient spec

- quint/src/parsing/ToIrListener.ts
This is a small refactor supporting #1082
Add a helper function to generate location IDs and register them into
the source map. These must always go together, so adding the two into
the same function saves a number of lines and makes the code safer since
it ensures we won't miss a needed addition to the map.
-------
- [-] Tests added for any new code
> Refactor ToIrListener id generation

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/flattening.ts
- quint/src/repl.ts
- quint/src/runtime/compile.ts
- quint/test/flatenning.test.ts
- quint/test/runtime/compile.test.ts
This fixes the issue encountered by Jure during the Quintshop. The problem was: we used to add incremental declarations/expressions to the last module in the list of modules, because the last module was always the `__repl__` module. When we [stopped requiring a `__repl__` module](https://github.com/informalsystems/quint/pull/1039), that became a problem, because not necessarily the last module is the actual main module that was loaded. This PR makes it so the new declarations are always added to the main module.
The reason it works when the file is imported, and not loaded via CLI, is because once no module is specified in the CLI (nor in an annotation inside the file), we introduce a `__repl__` module as the last module, and that is the main one even if you type import …
> Fix problem with loading module in the REPL

- quint/README.md
Add OpenJDK >= 17 that is required by `quint verify`.
> add a link to JDK

- quint/apalache-dist-tests.md
- quint/apalache-tests.md
- quint/io-cli-tests.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/simulation.ts
Addresses (1) of #1121:
Print pretty messages in `quint verify`, similar to `quint run`
> Print pretty messages in `quint verify`

- CHANGELOG.md
- quint/src/flattening/flattener.ts
- quint/src/flattening/fullFlattener.ts
- quint/test/flattening/flattener.test.ts
- quint/test/flattening/fullFlattener.test.ts
This fixes #1141 and pays a tech debt: instead of relying on toposort to fix flattening mistakes, we now put the flattened definitions in topological order.
> Flatten definitions in topological order without relying on toposort

- vscode/quint-vscode/.vscode/launch.json
Add a VSCode launch config for the VSCode extension.
This adds a nice little ⏯️ button in VSCode, that can be used to simultaneously
* launch the VSCode extension in debug mode, and
* attach a second debugger to the LSP server.
Found this very useful for debugging.
> Add VSCode launch config for the VSCode extension

- doc/builtin.md
- quint/src/builtin.qnt
Fix a typo in `foldl` builtin docs
Noted by @mpoke during the Quintshop
> Fix a typo in `foldl` builtin docs

- examples/solidity/GradualPonzi/gradualPonzi.qnt
- quint/cli-tests.md
- vscode/quint-vscode/server/package.json
This PR does 2 small things:
1 - Set the seed to produce a counterexample for one of the gradual ponzi invariants, just found by [CI](https://github.com/informalsystems/quint/actions/runs/6087542373/job/16516330316) in my latest merge.
2 - Fix the package name for quint language server, which should include the `@informalsystems/` prefix
> Set seed in CI and fix server package name

- CHANGELOG.md
- quint/src/flattening/fullFlattener.ts
- quint/src/names/unshadower.ts
- quint/test/flattening/fullFlattener.test.ts
- quint/test/names/unshadower.test.ts
This fixes #802 by running a pass that renames shadowed names before flattening. We currently don't allow arbitrary shadowing, but it is possible to have shadowing between different modules' definitions, as in the example from the issue.
PS: If we decide to allow arbitrary shadowing, this solution should also work for that. We would only need to remove the current shadowing checks from the name resolution step.
> Rename shadowed names to unique names

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/itf.ts
- quint/test/itf.test.ts
This PR update the ITF trace format, according to the change made in Apalache, see https://github.com/informalsystems/apalache/pull/2733. As a result, the ITF writer always writes integers in the format `{ '#bigint': 'num' }`. We still parse JS numbers for backwards compatibility.
> Serialize big integers in ITF traces as an object

- .github/workflows/main.yml
The CI task for linting VSCode plugin files is not currently using the local quint version. This causes problems when the published npm version is not compatible with the unpublished VSCode plugin version, causing errors like [this](https://github.com/informalsystems/quint/actions/runs/6172999525/job/16754376101?pr=1143). I copied the setup from the unit tests task to the linting task to make sure we can run linting in the CI in this scenario.
- [-] Tests added for any new code
> Fix CI issue when linting the VSCode plugin

- quint/apalache-dist-tests.md
- quint/src/cliCommands.ts
- quint/src/quintVerifier.ts
- quint/src/verbosity.ts
To avoid cluttering output when invoking `quint verify`, log messages related to obtaining and launching Apalache only at `--verbosity` >=4.
Closes #1121
> Log Apalache distribution-related `verify` messages only at --verbosity >=4

- examples/cosmos/tendermint/Tendermint.qnt
- examples/cosmos/tendermint/TendermintModels.qnt
- examples/cosmos/tendermint/TendermintTest.qnt
A one-liner that fixes the parameters in a Tendermint instance: The same process should not be both correct and faulty
> one line fix

- README.md
- editor-plugins/vim/README.md
- editor-plugins/vim/quint.vim
- vscode/quint-vscode/server/README.md
I've added some instructions on how to setup neovim with LSP. I'm not a neovim user, and my configuration is done through NixOS (home-manager), so I'm not 100% sure this instructions are the right way of doing things in a normal unix system. @konnov can you try them out, maybe?
- [-] Tests added for any new code
> LSP configuration for Neovim

- CHANGELOG.md
- doc/quint.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
Add a `--random-transitions` flag to `verify`, to run Apalache symbolic simulator instead of BMC.
Closes #1185
> Add --random-transitions to run Apalache symbolic simulator

- CHANGELOG.md
- quint/src/static/callgraph.ts
- quint/test/static/callgraph.test.ts
Fixes #1183.
Our topological sorting does not considering the overrides inside instance statements (i.e. `ConsumerChains = consumerChains`), so the effect checker tries to compute effects for the name `ConsumerChains` before inferring effects from the instance statement. This fix for the toposort makes the declarations be visited in the correct order, and then the effect checker doesn't crash anymore.
This is related to what we do here:
https://github.com/informalsystems/quint/blob/726f85305988263ab08d01e8e30c6487a56dd67c/quint/src/names/collector.ts#L145-L146
That is, the name actually refers to the ID of the expression assigned in the override, and therefore this expression has to depend on the instance statement. This is quite weird, but it works and I don't have other …
> Add constant -> instance dependency to callgraph

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/runtime/impl/compilerImpl.ts
Our new flattener process is still not done incrementally (https://github.com/informalsystems/quint/issues/1103). This will likely be a hard problem to solve.
Because of the re-flattening on each REPL evaluation (since it is not incremental), definitions from instances get fresh ids on each evaluation. This includes state variables, and therefore we had a problem (reported by @p-offtermatt on slack) where the values for variables were not persisting between evaluations.
The solution, for now, is to re-map the references to state variables from the old id to the new one. We do this by using the variable name which, after flattening, is guaranteed to be unique.
> Workaround for state vars from instances in incremental compilation (REPL)

- README.md
- doc/literate.md
Closes #449
@konnov reported that lmt was suitable to meet our current needs for supporting
"literate executable specs". This is valuable insofar as it shows how to achieve
the goal of replacing pseudo code snippets with working and tested fragments of
an executable formal specification. However, we had no documentation explaining
how to use the tool for this purpose. Now we do.
-------
> Document how to use lmt for writing literate executable specs

- quint/src/types/constraintGenerator.ts
- quint/src/types/substitutions.ts
- quint/test/repl.test.ts
- quint/test/types/constraintGenerator.test.ts
- quint/test/types/inferrer.test.ts
- quint/test/types/substitutions.test.ts
This implements items (3), (4) e (5) from https://github.com/informalsystems/quint/pull/1203. I found this problems for the effect checker, but the type checker has similar issues, so this fixes them.
> Apply improvements from effects system to the type system

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/server/src/parsing.ts
- vscode/quint-vscode/server/src/server.ts
This is a simple fix for the hanging on VSCode where it gave up on restarting the language server after 5 times. Even in unpredictable scenarios where we throw errors, this shouldn't happen.
> [LSP] Wrap parsing and analysis in `try...catch` block

- doc/lang.md
- quint/src/runtime/impl/compilerImpl.ts
- quint/test/runtime/compile.test.ts
- tutorials/.tours/sets.tour
- tutorials/lesson4-sets/sets.md
- tutorials/lesson4-sets/sets.qnt
- tutorials/lesson4-sets/sets.template.qnt
This is a follow-up to #1202. Since tuples are rewritten by the parser now, there is no need for special treatment in the simulator. This has also unblocked the old code in the tutorial 3.
> remove the tuple unpacking code

- CHANGELOG.md
- quint/src/cliCommands.ts
The `checker.tuning` config key was previously fully overridden in code.
Change this to only override the appropriate fields.
> Properly override `checker.tuning`

- doc/quint.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
Two fixes for `--apalache-config`:
* usage message erroneously mentioned HOCON as supported, when we only parse JSON from Quint
* wrap reading + parsing the config file in a try/catch block
Fixes #1215
> Fixes for `--apalache-config`

- doc/quint.md
The link, as is, does not work for me and brings me to a 404. This patch fixes it for me.
> Fix broken link

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
- Error reporting was changed to show more errors at a time, instead of having a lot of phases (#1220)
- The language server should no longer crash when there is a crash on quint
functions (#1205)
- Fixed a problem where errors in one file were being reported in other files
related to it (#1224).
> VSCode Release v0.10.0

- examples/language-features/option.qnt
- quint/src/cliCommands.ts
- quint/src/graphics.ts
- quint/src/parsing/quintParserFrontend.ts
- quint/src/quintAnalyzer.ts
- quint/src/repl.ts
- quint/src/runtime/compile.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/src/runtime/impl/runtimeValue.ts
- quint/test/runtime/compile.test.ts
Closes #1033
Adds support for sum types to the compiler (and so the simulator):
- Generalizes the REPL so it can compile all the declarations parsed out of its
input, instead of just the last one (required to enable sum type declarations
to be entered in the REPL).
- Adds graphics for pretty printing variants.
- Adds evaluation of constructors, requiring a new runtime value to represent
variants.
- Adds evaluation of match expressions, which eliminate variants.
The history is clean enough that it would probably help to review by commit.
> Add support for sum types in the simulator

- README.md
- doc/faq.md
Since we keep receiving similar questions about several constructs, I have added a page with explanations. In the future, this material should migrate into something more organized such a book.
> add frequently asked questions

- CONTRIBUTING.md
This adds a instruction to "manually" publish the [@informalsystems/quint-language-server](https://www.npmjs.com/package/@informalsystems/quint-language-server) package after publishing the VSCode plugin. We should include this in the script at some point.
P.S. I ran this for `v0.11.0` already, it is all good.
> Add publishing instruction for the language server npm package

- quint/src/parsing/ToIrListener.ts
- quint/src/types/specialConstraints.ts
This was causing noise in PR review changesets due to
linter warnings.
-------
> Fix line length lints

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/runtime/testing.ts
- quint/testFixture/_1051manyTests.qnt
Closes #1263
Taking the example from the issue,
```bluespec
module manyTests {
var x: int
action init = x' = 0
run firstTest = init.then(x' = 1).then(all { assert(x == 1), x' = x })
run secondTest = init.then(x' = 2).then(all { assert(x == 2), x' = x })
}
```
After compiling `quint` with the change from this PR, the saved traces correspond to each test case.
```sh
$ quint test --output {}.itf.json manyTests.qnt
manyTests
ok firstTest passed 1 test(s)
ok secondTest passed 1 test(s)
2 passing (9ms)
$ cat *.itf.json | jq -c .states
[{"#meta":{"index":0},"x":{"#bigint":"0"}},{"#meta":{"index":1},"x":{"#bigint":"1"}}]
[{"#meta":{"index":0},"x":{"#bigint":"0"}},{"#meta":{"index":1},"x":{"#bigint":"2"}}]
```
> fix: reset trace recorder at beginning of each test run

- CHANGELOG.md
- quint/src/effects/builtinSignatures.ts
- quint/test/effects/inferrer.test.ts
The current effect for `match` (or `matchVariant`) is currenlty overpermissive. We should ensure that all possible branches result in the same variable updates, as we do in if-then-else and `any`. This changes the effect signature for `match` so the updates are consistent across eliminators.
> Fix effect signature for the `match` operator

- CHANGELOG.md
- doc/builtin.md
- doc/lang.md
- examples/language-features/counters.qnt
- quint/src/builtin.qnt
- quint/src/quintError.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/test/runtime/compile.test.ts
Closes #594. Similar to the behavior described in #594, @josef-widder and I have noticed that the current semantics of `A.then(B)` is tricky when `A.then(B)` evaluates to `false`. In this case, it is not clear whether `A` or `B` evaluated to `false`. This makes it hard to debug long runs. In general, engineers expect that a sequence of steps cannot just stop somewhere in the middle, which is how `A.then(B)` works now. This looks a bit like a deadlock, especially when we have non-deterministic choices or `any`.
This PR is changing the runtime semantics of `A.then(B)` in the simulator to the behavior that I believe is more consistent with normal programming languages. Namely, if `A` evaluates to `false`, then `A.then(B)` emits a runtime error saying that a computation cannot continue. …
> Change the runtime behavior of `then`

- quint/src/runtime/impl/runtimeValue.ts
- quint/test/repl.test.ts
Following [this discussion](https://github.com/informalsystems/quint/pull/1304#discussion_r1425177604), here are defensive checks in runtime values, so we don't have to test for exact type in the compiler code. Interestingly, one of the tests has triggered an exception, since REPL passes through type-incorrect expressions. (We should disable that at some point).
> introduce type fences in runtime values

- doc/README.md
Followup to #1308, in which I broke all these links.
Thanks to @jorpic for pointing this out:
https://github.com/informalsystems/quint/commit/53b13316c46fe27c7532d56429ebe3bddfeb4a85#commitcomment-135330468
> Fix links on doc/README.org

- doc/builtin.md
- quint/src/builtin.qnt
I had a misunderstanding of the behavior of `allLists` and that was reflected in the docs I wrote. This fixes the doc.
> Fix API documentation for `allLists`

- examples/spells/BoundedUInt.qnt
Resolves a TODO by replacing the record-based representation using a
non-empty error string with a result sum type.
This is to be used in ongoing work on modeling contracts.
-------
> Use result type for BoundedUInt

- quint/src/simulation.ts
This is a followup to https://github.com/informalsystems/quint/pull/1340 since I found a (hacky) way to include locations in the reported errors. We should remove this when #1052 is fixed and errors can be reported normally. The reason for this is that it is very hard to find where runtime errors could potentially happen in a big spec, and having the location info makes all the difference.
For this, we compute the locs for the error while we still have access to the `compileFromCode` inputs and outputs, and then manipulate the `QuintError` to include those locs in a hacky way:
1. We remove the (optional) `reference` field, so no locs are included in the final error - since those would be messed up anyaway
2. We then include the locs as text + highlights in the error …
> Improve runtime errors in the simulator

- quint/src/cliCommands.ts
- quint/src/simulation.ts
Address the cleanups noted in discussion of #1340
> Cleaning up branching logic in runSimulator

- CHANGELOG.md
- quint/src/cliCommands.ts
- quint/src/effects/base.ts
- quint/src/effects/inferrer.ts
- quint/test/effects/base.test.ts
- quint/test/effects/inferrer.test.ts
Closes #1356
The originating issues was caused by fairly subtle error in our unification algorithm for the effect checker, which was making an invalid occurs check. This error was hard to spot, because (I think) we are not used to thinking of unification sets! I think we usually think of unification in terms of the "geometric structure" of the syntactic terms being unified. E.g., when unifying lists, `[A, B] =.= [C, D]` iff `A =.= C, B =.= D`, and `A =.= [1, 2, A]` should fail an occurs check because it would require unifying `A` with a term that includes itself as a sub-term. However, the extensional nature of sets invalidates the "evident" geometric intuition that guides us in the previous examples. `A =.= B ∪ C ∪ A` is true iff `B =.= C =.= A`.
This is also explained in a bit more …
> Remove erroneous occurs check from "effect entity" unfication

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/cliCommands.ts
@p-offtermatt just reported a problem on slack where we stopped producing ITF on successful runs - we are currently only producing them in violations. This fixes the problem and adds an integration test for this previously uncovered scenario.
> Fix ITF not being produced on successful runs

- quint/src/ir/IRTransformer.ts
- quint/src/ir/IRVisitor.ts
- quint/test/ir/IRTransformer.test.ts
- quint/test/ir/IRVisitor.test.ts
Followup for #1371
Contributes to #1298 
I forgot to add visitor logic for the parameter type annotations
> Fix visitor and transformer for params

- quint/package-lock.json
- quint/package.json
- quint/src/ir/IRTransformer.ts
- quint/test/types/aliasInliner.test.ts
There was some mutation happening via the transformer, which was
wreaking havoc on attempts to complete #1298.
Apparently it was also somehow leading to incorrect printing of sum
type variants. I haven't had time to investigate why, but deep cloning
the original object must be safer and it is fixing a blocking problem in
ongoing work in #1298.
Since the cases in which this causes problems are quite subtle, I havent
been able to figure out how to test this directly.
**NOTE** that this is on top of #1382, and that needs to be merged in first
(and this then rebased). Only [31d5654ee777c5dc21fb234b6e9098b55878d367](https://github.com/informalsystems/quint/commit/462dcfa6eaaa02dd71f0e11c1e85506f059eb853) is new here.
> Ensure transformations can't mutate the original object 

- doc/quint.md
- quint/apalache-tests.md
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/testFixture/ApalacheCompilation.qnt
Closes #1402
This also shares the flattening and extension logic between the
`compile` command and the `verifySpec` command.
Note that this presupposes #1406, and it will need to be rebased after that is merged in.
> Add q::* operators to compiled targets

- CHANGELOG.md
- quint/src/cliCommands.ts
This ensures that Sets are properly serialized in the JSON output. Needed for a follow-up PR I'll open in Apalache, where we start using the information about quantified variables in type schemes, which are represented as Sets. Related to #1398.
> Fix serialization of Sets

- CHANGELOG.md
- quint/src/graphics.ts
- quint/src/itf.ts
- quint/test/itf.test.ts
Fixes https://github.com/informalsystems/quint/issues/1411
After changing our unit type from the empty record to the empty tuple, I noticed some ugliness on the UI, where traces were being printed with sum-types like `None(())` or even `None("U_OF_UNIT)` when using `quint verify`. This PR fixes both of those!
> Fix user facing unit type

- .github/workflows/main.yml
- quint/src/effects/builtinSignatures.ts
- quint/src/names/base.ts
- quint/src/repl.ts
- quint/src/runtime/compile.ts
- quint/src/runtime/impl/compilerImpl.ts
- quint/src/runtime/impl/trace.ts
- quint/src/runtime/runtime.ts
- quint/src/runtime/testing.ts
- quint/src/simulation.ts
- quint/src/types/builtinSignatures.ts
Towards https://github.com/informalsystems/quint/issues/1379
Many ideas involving debugging and mbt-oriented features require updates in the compiler. Currently, the `compilerImpl.ts` file is 1833 lines long, and I guess modern LSP solutions are not prepared for files this big, because my editor is struggling a lot!
So I'm trying to improve this file a bit. I start by removing the concept of shadow variables. I think we used to have many shadow variables, and therefore we introduced this abstraction, but right now we only have the trace, and I think it is quite unecessary to have it instead of simply keeping the trace in an attribute.
I also extracted trace manipulation logic to a new file.
Behavior shouldn't change, this is simply a refactor.
> Refactor traces in the compiler

- quint/apalache-tests.md
- quint/io-cli-tests.md
- quint/src/apalache.ts
This is a bump for apalache, as a new version was released today and it is relevant to Quint.
Among other fixes, the compiled TLA+ modules are now type annotated, so I also updated the integration test expectations.
> Bump apalache version

- CHANGELOG.md
- quint/src/effects/NondetChecker.ts
- quint/src/effects/inferrer.ts
- quint/src/types/inferrer.ts
- quint/test/effects/NondetChecker.test.ts
This is a hotfix for a mistake I made in https://github.com/informalsystems/quint/pull/1431.
I thought I could assume all types were present at that point, but as those checks run in the same phase as the type checker, it can be the case that there are type errors and, therefore, missing types. This was causing the tool and the language server to crash in those scenarios, in their latest versions released after the linked PR.
We strive for accumulating as many errors as we can before giving up analysis and reporting them. So this PR tries to report nondet errors when it can (types and lookup table entries are found), and otherwise just safely skip the check since surely a type error is already in the list of errors to be reported on exit.
> Hotfix: Handle cases where table entries or types are missing

- CHANGELOG.md
- quint/src/runtime/testing.ts
- quint/src/runtime/trace.ts
- quint/src/simulation.ts
Closes #1456 
In https://github.com/informalsystems/quint/pull/1365 I prioritized performance over memory consumption without thinking too much about it and it was a bad choice. I've heard complains from three people (@josef-widder, @cason and @konnov) about a ridiculous increase in memory consumption by Quint, and this was the cause.
This PR fixes the problem by sacrificing a bit of performance (making a sort operation at every trace) and therefore not having to store all traces found (which would enable a single sorting operation).
Most importantly, the new approach should only impact performance when the new `--n-traces` flag is used. All previously existing operations should no longer be affected by this change. This was the biggest problem, since even when the flag …
> Hotfix for high memory usage

- CONTRIBUTING.md
- Makefile
- README.md
- docs/codetour/lesson3-anatomy/coin.template.qnt
- docs/codetour/lesson3-anatomy/coin.xml
- docs/pages/docs/architecture-decision-records/adr008-managing-apalache.md
- docs/pages/docs/lessons/coin.md
- docs/pages/docs/rfcs/rfc001-sum-types.md
- docs/pages/docs/rfcs/rfc001-sum-types/rfc001-sum-types.org
- docs/pages/docs/rfcs/rfc001-sum-types/rfc001-sum-types.tex
- docs/pages/docs/rfcs/rfc007-foreign-calls.md
- docs/roadmap.md
- examples/classic/sequential/BinSearch/BinSearch.qnt
- examples/verification/README.md
- quint/src/apalache.ts
- quint/src/itf.ts
- quint/src/quintVerifier.ts
- quint/src/static/toposort.ts
Apalache has recently moved from the `informalsystems` to the `apalache-mc` organization.
> Fix Apalache repository URL

- examples/.scripts/run-example.sh
- examples/README.md
- examples/classic/distributed/TeachingConcurrency/teachingConcurrency.qnt
This adds a simple concurrent algorithm described by Lamport in https://lamport.azurewebsites.net/pubs/teaching-concurrency.pdf.
It provides an arbitrary-N module and a concrete-N instance.
It shows how to use temporal formulas and check for (eventual and correct) termination in the verifier.
> examples: add Lamport's concurrency teaching algorithm

- CHANGELOG.md
- quint/src/apalache.ts
We just released a version of Apalache that includes an `apalache-mc.bat` file, enabling Quint to start that file in order to run Apalache on Windows.
This PR bumps the Apalache version so we can use that, and then adds CHANGELOG entries related to Windows so we can cut a release
> Bump Apalache to 0.45.6

- CHANGELOG.md
- quint/apalache-dist-tests.md
- quint/src/apalache.ts
- quint/src/cli.ts
- quint/src/cliCommands.ts
- quint/src/compileToTlaplus.ts
- quint/src/quintVerifier.ts
Since every release of Apalache requires a PR in Quint, this PR introduces the option `--apalache-version`. This option allows the Quint users to pull different versions of Apalache without waiting for a new release of Quint. For instance, the new version of Apalache v0.47.0 downgrades the version of z3.
> Add the option `--apalache-version` to `quint verify`

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
> VSCode Release v0.14.7

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
Due to a problem in our still very manual release process, the release 0.14.7 (#1528) didn't properly update the Quint dependency inside it, so I'm cutting a new one.
> VSCode Release v0.14.8

- CHANGELOG.md
- editor-plugins/highlight.js/quint.js
- vscode/quint-vscode/syntaxes/quint.tmLanguage.json
This adds supports for highlighting an hashbang line as a comment, in vscode and in highlight.js.
> editor-plugins: add hashbang line highlighting

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
> VSCode Release v0.14.9

- docs/README.md
I've fixed the broken quint-cheatsheet.pdf link in the [README.md](https://github.com/informalsystems/quint/blob/main/docs/README.md) file.
> fixed broken link for quint-cheatsheet.pdf in README.md

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/runtime/impl/VarStorage.ts
This fixes a bug where traces other then the first one when `--n-traces` > 1 had the wrong metadata values on the first state (inheriting them from the last execution instead of starting from `init`).
> Hotfix: Properly reset metadata variables

- quint/src/runtime/impl/runtimeValue.ts
- quint/test/runtime/compile.test.ts
Empty domains and empty ranges in the setOfMaps operator now give Set(Map()) and Set() respectively, like TLC.
Fixes #1523
> Fixes  #1523

- CHANGELOG.md
- quint/apalache-dist-tests.md
- quint/apalache-tests.md
- quint/src/apalache.ts
- quint/src/itf.ts
- quint/test/itf.test.ts
Our CI setup is not super great, and picks up the latest version of Apalache for the integration tests (not using the actual version stablished by Quint). We had breaking changes in https://github.com/apalache-mc/apalache/pull/3041 in the Unit representation. This PR bumps Apalache and changes things to work with the latest UNIT representation.
> Bump Apalache to 0.47.2 and update UNIT representation

- docs/pages/docs/language-basics.mdx
I’ve corrected a few typographical errors in the documentation:
1. "defintions" has been updated to "definitions" in the "Assignments have no order" section and other places where it appeared.
2. "get's" has been corrected to "gets" in the "Non-determinism" section: "there's non-determinism when a user gets to decide".
3. The typo "defintions" (again) has been fixed to "definitions" in the "Modes" section.
4. "oportunites" has been changed to "opportunities" in the "optimization opportunities" sentence.
> docs: fixing typos across documentation

- docs/pages/docs/development-docs/architecture-decision-records/adr001-transpiler-architecture.md
- docs/pages/docs/development-docs/architecture-decision-records/adr005-type-system.md
- docs/pages/docs/development-docs/architecture-decision-records/adr008-managing-apalache.md
- docs/pages/docs/development-docs/rfcs/rfc007-foreign-calls.md
- docs/pages/docs/quint.md
- docs/roadmap.md
- quint/README.md
- quint/src/cliCommands.ts
- quint/src/itf.ts
Hi! This PR addresses and fixes broken links across various documentation files, ensuring all references to apalache.informal.systems are updated to apalache-mc.org. The changes are consistent with the project's style and have been verified to resolve the 404 errors.
> docs: fix broken links across multiple documentation files

- examples/cosmos/ics20/README.md
- quint/src/effects/base.ts
- quint/src/flattening/flattener.ts
- vscode/quint-vscode/server/src/rename.ts
> chore: fix some typos

- CHANGELOG.md
- examples/classic/distributed/ewd426/check_with_tlc.sh
- quint/apalache-tests.md
- quint/src/cliCommands.ts
- quint/src/ir/initToPredicate.ts
- quint/src/quintError.ts
- quint/testFixture/ApalacheCompilationError.qnt
Closes https://github.com/apalache-mc/apalache/issues/2863. Towards https://github.com/informalsystems/quint/issues/1424
This fixes an old issue where we failed to properly transpile Quint into TLA+ as Quint init definitions are actions with assignments, while TLA+ expects predicates with equalities for the initial state.
The strategy is:
1. Collect all definition names that are called from `q::init`, recursively
2. Iterate again, now replacing assignments whenever they are found inside of those definitions
3. In this second iteration, if this definitions are ever found also outside of the `q::init` context (being referred to by names outside of the tracked scope), we check if they have assignments (mode is `action`) and, if so, report an error.
- If we update this type …
> Convert init into predicates when compiling to TLA+

- examples/spells/basicSpells.qnt
I know it's supposed to go into the `rareSpells` first, but given that there's already a `max` one in `basicSpells`, I figured it would better for them to go together.
> spell: add `min` alongside existing `max`

- quint/src/cliCommands.ts
- quint/testFixture/ApalacheCompilation.qnt
We recently added the conversion of `init` actions into TLA+ predicates when transpiling. This would result in an error in the rare scenario where `init` is used in an action context (other than the one being converted - for example, inside `step`).
I now realize this "rare scenario" happens often in runs. However, runs are discarded by Apalache anyway and there's no translation of runs into TLA+. So what I'm doing now is just dicarding the runs before we go into this init conversion step. This happens only on transpilation to TLA+.
> Prevent init errors from being reported for runs

- .github/workflows/release.yml
> ci: wait for npm in ubuntu runner

- CHANGELOG.md
- quint/src/quintRustWrapper.ts
I noticed we were not showing the error locs from errors coming from Rust, even tho the info was there. Turns out it was just a conversion issue.
No tests as we haven't setup the integration tests yet - will do it soon.
> Fix error reference conversion from Rust result

- CHANGELOG.md
- evaluator/fixtures/instances.qnt
- evaluator/src/evaluator.rs
- evaluator/tests/simulator_tests.rs
This fixes a problem where we'd get an error about uninitialized constants even if they were properly initialized. I tried adding an optimization when writing the Rust version, but it was wrong. I thought we could just evaluate pure values in a "fake" environment, as they can't reference variables in any way; and then just save that value in the cache. Now I realize we still need the closure behavior as it ensures that the value is only evaluated in the correct context, where the constants are properly set - since even pure vals can refer to constants.
This was already the behavior in the Typescript, I was just a bit naive in the rewriting and we didn't have test coverage for this scenario yet.
> Fix problem with missing constants being cached

- examples/classic/distributed/ewd426/README.md
- tlc/check_with_tlc.sh
This improves the TLC script interface a bit, namely:
1. Taking the file as a positional argument instead of under a flag
2. Taking the invariant as an expression, as in `quint run`
3. Using `--workers=auto` as default
4. Taking init and step optionally, as well as `main`, which then produces a `tla` and `cfg` file with that main's name so TLC won't complain the module doesn't match.
> Improve interface of `check_with_tlc.sh`

- docs/pages/docs/lang.md
This PR addresses issue #1619, which identified that the `getOnlyElement` method for sets is missing from some of the Quint documentation.
- Added documentation for `getOnlyElement` to the `docs/pages/docs/lang.md` file in the "Set operations" section
- The Quint cheatsheet also needs to be updated, but it appears to be in PDF format only.
- Verified that the `getOnlyElement` method is now documented in the `lang.md` file
- Closes #1619
If the source for the cheatsheet is not available or if there's a different process for updating the cheatsheet, please let me know and I'll follow that process to complete the documentation update.
> Add documentation for `getOnlyElement` method for sets

- docs/README.md
This PR fixes issue #1617 by updating the links in docs/README.md to point to the correct file locations.
The main problem was that many documentation files had been moved to the docs/pages/docs directory, but the links in docs/README.md were still pointing to the old locations. This PR updates all links to point to the actual locations of the referenced files.
- Updated links to language-related documentation
- Updated links to tooling documentation
- Updated links to design and development documentation
Closes #1617
> docs: fix broken links in docs/README.md

- docs/pages/docs/lang.md
This pr removes the outdated and duplicate entry for 'Action' in the modes table found in `quint/docs/pages/docs/lang.md`. 
Closes #1508
> Fixed the duplicate entry for 'Action' in the modes table of the language manual

- evaluator/Cargo.lock
- evaluator/Cargo.toml
- evaluator/src/main.rs
- evaluator/src/simulator.rs
- quint/src/quintRustWrapper.ts
- quint/src/runtime/impl/evaluator.ts
After the lastest Quint release last week, I realized I both forgot to bump the evaluator before (breaking compatibility with the progress bar changes that got released) and to test the integration with the newer features (like speed and trace length reporting). We need to add some integration tests to CI - I'll set that up later in the week.
This fixed the issues for now. I'll release evaluator v0.2.0 once this is merged and then bump the version on the typescript side and cut a new NPM release.
> Add samples and trace length stats to rust simulator

- CONTRIBUTING.md
I was going through the `CONTRIBUTING.md` guide and noticed that some of the links were broken.
This PR fixes it.
> Fix links to the development docs in the contributing guide

- vscode/quint-vscode/CHANGELOG.md
- vscode/quint-vscode/package-lock.json
- vscode/quint-vscode/package.json
- vscode/quint-vscode/server/package-lock.json
- vscode/quint-vscode/server/package.json
- Quick fix for common syntax error on map type definitions (#1682)
> VSCode Release v0.16.0

- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/codetour/Makefile
- docs/content/docs/lessons/coin.md
- evaluator/flake.nix
- evaluator/src/builtins.rs
- evaluator/src/evaluator.rs
- evaluator/src/value.rs
- evaluator/tests/evaluation_tests.rs
- examples/tutorials/repl/Makefile
- quint/package.json
This fixes CI breaking in main:
1. Our clippy linting for Rust was breaking for a while due to it being updated upstream (I guess, in the CI workflow we use). I updated the flake (not in the best way possible, but it works) so developers like me have the 1.88 version, which includes new linting rules which are also fixed in this PR
2. Generating files was breaking due to the recent website changes that moved the `pages` folder to `content`. I then also noticed I forgot to update some links, which I did here as well.
> Fix CI issues

- docs/components/home/index.tsx
I know what's true of Quint here is true of all Spec Languages and so that is more correct but this is on the Quint site homepage and theres a lot going on that's already a little hard to parse so to simplify and guide the eye I thought they should all say Quint on the left of the table
> site: Spec Languages -> Quint

- docs/content/docs/getting-started.mdx
> Fix typo in getting-started.mdx

- CHANGELOG.md
- quint/apalache-dist-tests.md
- quint/src/apalache.ts
This PR bumps the default version of Apalache to 0.47.3. It contains an important improvement in Z3:
```
Upgrade Z3 to 4.13.4 (restores linux/arm64 support), see #3057
```
> Bump apalache to 0.47.3

- CHANGELOG.md
- quint/apalache-dist-tests.md
- quint/src/apalache.ts
Sorry about bumping Apalache quite often over several days. There were quite important changes w.r.t. `apalache::generate`. After updating to 0.49.1, it should work pretty well.
> Bump apalache to 0.49.1

- CHANGELOG.md
- quint/src/parsing/ToIrListener.ts
- quint/src/parsing/parseErrors.ts
- quint/src/quintError.ts
- quint/test/parsing/quintParserFrontend.test.ts
Fixes #1677
I couldn't find how to not get this debug message (`[DEBUG] generating undefined expr to fill hole in: vala={foo:1,foo:2}`), it seems to be extremely trivial but since I'm not familiar with the codebase it's kinda hard to find, any help on this would be very appreciated.
> Duplicate field on records should return parse error

- CHANGELOG.md
- quint/src/runtime/impl/nondet.ts
- quint/test/repl.test.ts
Hello :octocat:
I realized that my check for empty sets on `oneOf` was not working properly, and I found the root cause to be this `isEqual` comparison that was not working as I expected.
> Fix empty sets not being detected properly in new oneOf

- CHANGELOG.md
- quint/apalache-dist-tests.md
- quint/src/apalache.ts
Increasing GRPC message size in Apalache to 1 GB, as I have just observed a Quint spec that have hit the current limits: https://github.com/apalache-mc/apalache/pull/3155
> Bump apalache to 0.50.2

- CHANGELOG.md
- quint/apalache-tests.md
- quint/src/types/aliasInliner.ts
- quint/src/types/constraintGenerator.ts
- quint/src/types/substitutions.ts
- quint/src/types/typeApplicationResolution.ts
- quint/testFixture/apalache/genericRowParam.qnt
- quint/testFixture/apalache/inferredStateVar.qnt
- quint/testFixture/apalache/polyStateVar.qnt
This fixes https://github.com/informalsystems/quint/issues/1698 and closes https://github.com/informalsystems/quint/issues/691 as we actually don't need to ensure that anymore, as long as we give Apalache a concrete inferred type (more on that in #1755)
There are three nasty bug fixes here, covered by the following integration tests that all break on main with Apalache errors:
A note here on "bug": one of this was an actual bug, but the other two were more consequences of us not planning to allow polymorphic types for state variables. This constraint was a big problem for the new library/framework we are working on (launch is soon!), as we want to define polymorphic variables there that will be specialized as the library's users define their application-specific types. …
> Apalache integration fixes

- .github/workflows/integration.yml
- CHANGELOG.md
- quint/package.json
- quint/rust-backend-tests.md
- quint/src/quintRustWrapper.ts
GitHub seems to validate tokens regardless of the resource visibility. If the user has an invalid token in their environment, downloading the rust backend will fail even though it's publicly available in the project's release assets.
This patch removes the GITHUB_TOKEN from the requests to list and download assets from GitHub to avoid unauthorized issues. Moreover, it includes an integration test that verifies quint is able to download the latest rust banckend for further coverages of this workflow.
Closes https://github.com/informalsystems/quint/issues/1763.
> Remove GH bear token from rust backend download

- docs/content/posts/alpenglow.mdx
The current wording in the Alpenglow blog post leads inexperienced users to believe that by running `quint test statemachine.qnt` all tests in the file will be executed, which isn't true. The test command must be called with the spec file and the main module in this example.
Moreover, it mentions that `quint test` can be used in CI to run tests, which is true but, the wording is overloaded by other commonly used tooling, like `npm test` for example, where the expectation is that by simply running `test` it runs all tests in the codebase. That isn't true for quint (yet), so it's worth expanding to the full command one would use in CI right now.
~Finally, the final spec ended having the run [called](https://github.com/informalsystems/Alpenglow-spec/blob/main/statemachine.qnt#L453) …
> Clariy `quint test` commands in the Alpenglow blog post

- CHANGELOG.md
- quint/io-cli-tests.md
- quint/src/repl.ts
When entering the repl, if expressions exist in the form of /*! expr !*/ comments in the quint source code, those are evaluated by the repl upon loading the file. However, the repl won't show what commands were executed, only their output.
This patch changes this behavior so that when loading a module, unless in quiet mode, the reply will show which commands were executed after loading.
This changes the output from:
```
$ quint -r examples/tutorials/repl/kettle.qnt
Quint REPL 0.28.0
Type ".exit" to exit, or ".help" for more information
4
Set(2, 4, 6)
32
212
false
true
-40
104
runtime error: error: [QNT502] Variable temperature not set
temperature
^^^^^^^^^^^
```
To:
```
$ quint -r examples/tutorials/repl/kettle.qnt
Quint REPL 0.28.0
Type ".exit" to exit, or ".help" for more information …
```
> Print commands in file's expression history

- CHANGELOG.md
- quint/src/repl.ts
- quint/test/repl.test.ts
The repl supports trimming the prompt and the continue prompt prefixes when copying and pasting previous expressions form the repl. However, the '...' prefix of multi-line expressions confuses the interpreter into thinking that those lines are special commands instead.
This patches fixes the repl's line handler so that lines starting with '...' continue prompt prefix are interpreted as quint expressions, thus allowing for copying and pasting multi-line commands from the repl itself.
> Fix copy and past for multi-line expression

- evaluator/Cargo.toml
- evaluator/src/main.rs
- evaluator/src/simulator.rs
This patch receives a `nthreads` input from the quint CLI. If present and more than 1, it runs simulations in parallel using the specified number of threads.
> Introduce parallel simulations

- docs/app/layout.tsx
Removing the Choreo Launch banner from the website since the date has past. We still have a [new] badge by Choreo's tab which should draw people's attention.
I'm keeping the component for the banner as we'll likely have other announcements in the future, and then we can re-use that.
Preview here: https://gabriela-website-remove-banner--quint-docs.netlify.app/
> [website] Remove announcement banner

- .github/workflows/integration.yml
- .github/workflows/release.yml
- quint/package.json
- quint/rust-backend-tests.md
Rust integration tests are flaky when running on a per PR basis due to the GH API rate limit that prevents us from downloading the evaluator multiple times in parallel. This patch moves the integration test to a pre-release step so it runs only as a sanity check before releases.
> Move rust integration tests to a pre-release step

- quint/src/quintRustWrapper.ts
Bumping rust as I've just cut a release for it https://github.com/informalsystems/quint/actions/runs/18044128929
Following-up, a PR with the typescript release
> Bump rust evaluator to v0.3.0

- quint/io-cli-tests.md
I've forgot to remove the REPL banner from the test output before and now the test fails on new versions of Quint :facepalm: 
Here's the fix
> Remove REPL version line from test expectation

- .github/workflows/release.yml
The Rust backend keeps failing CI while trying to download the lastes binaries from the GH API. This patch comments out the integration tests from the release pipeline. We'll investigate a fix for it soon.
> Remove integration tests from the release pipeline
