informalsystems/quint

README.md
Proposed for 2 aims:
- More linear structure: we introduce the topic of syntax before we
explain the components of the syntax.
- Give an even more favorable tone in connections with TLA and TLA+
=> Add readme description suggestion

CHANGELOG.md, Makefile, quint/package-lock.json, quint/package.json, vscode/quint-vscode/server/package.json, vscode/quint-vscode/server/src/server.ts
- Updates and fills out package metadata
- Bumps version
- Changes name to be scoped under `informalsystems` organization
- Updates changelog
After this is merged, I'll cut a release from 648f2ad and release that to npm!
=> Prepare for NPM release

CHANGELOG.md, quint/README.md, quint/package-lock.json, quint/package.json
Cutting a new release to test release plan and to update installation
instructions and package description.
=> Release 0.5.0

tutorials/README.md
Since we have the VSCode extension published, I've updated the instructions in the codetour tutorial.
=> update codetour tutorial instructions

doc/quint.md
=> added missing bracket in md

CHANGELOG.md, quint/src/repl.ts, quint/test/repl.test.ts
Closes #497. Fix the bug reported by @bugarela at the standup.
=> fix #497: broken output for maps in REPL

README.md
[rendered file](https://github.com/informalsystems/quint/blob/61143dca7ff46fc8ccfc881d6eb8dd84e79eea1f/README.md)
=> Add badges to README for vscode and npm versions

tutorials/.tours/booleans.tour, tutorials/lesson1-booleans/booleans.md
The CodeTour file was missing and markdown was a bit outdated.
=> fix a few issues with the Booleans tutorial

README.md
cosmetic changes on the main page
=> fix the links and add emojis

CHANGELOG.md, quint/package-lock.json, quint/package.json
=> Release 0.5.2

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
PS: This also starts tracking 2 `package-lock.json` files for server/client.
- Signature help functionality showing docstrings (#485).
- Documentation overlays on hover (#512).
=> Release VSCode extension v0.1.1

CHANGELOG.md, quint/package-lock.json, quint/package.json
- A few productivity hacks in REPL (#557)
- Operator `fail` (#552)
- `assert` is now an action operator, not a run operator (#542)
=> Release v0.5.3

CHANGELOG.md, quint/package-lock.json, quint/package.json
- Re-release of v0.5.3 with proper packaging
=> Release v0.5.4

CONTRIBUTING.md
Disclaimer: This PR description is more of a rant, you can skip it.
I had plenty of issues with VSCode this week on both my computer and my laptop, and @konnov had the same thing happen to him. After having to fix this so many times, I found a minimal solution and decided to document it (initially for selfish reasons as I don't want to lose my mind over this (again) when I'm back from vacation :clown_face:, but I guess it's a nice practice anyhow).
Step 4. was really my nemesis on understanding this fix, as you can only imagine how much time it took me to realize I had to restart it twice.
=> Troubleshooting VSCode instructions

CHANGELOG.md, examples/solidity/Coin/Coin.qnt, quint/cli-tests.md
I have finally found an example for the next tutorial. It is simple enough and yet reasonable. We can also demonstrate various features with this example.
This example took me 1:30h to do. With a bit of experience and a right set of idioms this may become quite easy to do.
=> add the coin example

.github/workflows/README.md, .github/workflows/release.yml, CONTRIBUTING.md, quint/package.json
Closes #590
Closes #589
See the documentation added in this PR for details.
=> Add CI to cut release and publish quint package

.github/workflows/release.yml, CONTRIBUTING.md, quint/scripts/release.sh
Also adds a couple small fixes in the github workflow.
See the commit messages for explanation.
=> Add script to cut release of quint

tutorials/.tours/coin.tour
@pdini told me that we are missing the tour file for the tutorial 3. Indeed, I forgot to add it to git. Fixed that.
This file is automatically generated, so there is not much to review.
=> add the third tour

examples/language-features/booleans.qnt, quint/cli-tests.md
Used in integration tests, and also illustrates core boolean operator.
-------
=> Add booleans language features example

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
- Change parsing interfaces to support multiple modules (#547)
- Change static analysis interfaces to support multiple modules (#559)
- Change documentation overlays and code navigation to support multiple modules (#584)
- Add code action to fix mode errors (#619)
=> VSCode Release v0.1.3

.github/workflows/main.yml, .gitignore, CONTRIBUTING.md, vscode/quint-vscode/package.json
Thanks to @bugarela for the pointers.
=> Add followup tweaks and docs related to releasing the VSCode extension

tutorials/.tours/sets.tour
that was missing in the previous PR
=> add the codetour tutorial

tutorials/lesson4-sets/sets.md
=> Move a comma

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
- Updated compatible quint version, which includes breaking changes (#698).
=> VSCode Release v0.2.0

doc/previews.md
I just noticed the videos were switched
=> Fix preview order

README.md
Remove the "." at the end of one of the bullet points.
I come across this quite often, and it bothers me every time 😅
=> Remove extraneous punctuation

README.md
This PR adds the community section, similar to the Community section of Apalache.
=> update the landing page

README.md, examples/language-features/lists.qnt, examples/language-features/sets.qnt, quint/apalache-tests.md
=> Add integration tests with Apalache for list operators

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.3.0

examples/solidity/ERC20/erc20.qnt
Fixing the accidental type errors that are described in #789.
=> fix type errors

README.md
Just a feature table update. :white_check_mark: constants and update issue for discriminated unions (the current one was closed in favor of the new one).
=> Update feature table

examples/solidity/ERC20/erc20.qnt
I have found a few small issues when translating the Quint spec to the TLA+ spec
=> Small fixes in ERC20

quint/src/graphics.ts
I have renamed several things in #870, but VSCode has not saved them. Enabled autosave in VSCode, so it does not happen again,
=> forgotten changes in the pretty-printer

examples/cosmos/ics20/base.qnt, examples/cosmos/ics20/ics20.qnt
Closes https://github.com/informalsystems/apalache-team-services/issues/8
ℹ️ based on #858 – review that one first 😉 
Add 2 actions, one for timing out packets, and one for processing the timeout on the originating chain.
Add a test for proper timeout handling.
=> Add timeout handling to ICS-20 spec

examples/cosmos/ics23/ics23.qnt
=> Adding bluespec mode to ics23.qnt

examples/README.md, examples/classic/sequential/BinSearch/BinSearch.qnt, examples/classic/sequential/BinSearch/BinSearch10.qnt, quint/cli-tests.md
So far, we have not been testing the binary search example. This PR fixed that.
=> Updating the binary search example

examples/README.md, examples/solidity/SimplePonzi/simplePonzi.qnt, quint/cli-tests.md
Adding an example that is quite simple yet interesting.
=> add a simple ponzi example

examples/solidity/SimplePonzi/simplePonzi.qnt, quint/cli-tests.md
This PR extends the Ponzi example with interesting properties and tests.
=> expand on ponzi

LICENSE
It's a bit embarrassing, but we forgot to update the license file since 2021 %)
=> update the license file

examples/cosmos/lightclient/Blockchain.qnt, examples/cosmos/lightclient/typedefs.qnt
=> Liteclient rewrite: Blockchain.qnt

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.5.1

README.md
Add a youtube link to the gateway talk
=> add a link

quint/src/graphics.ts, vscode/quint-vscode/CHANGELOG.md
Fixes #967 
- [-] Tests added for any new code
=> Add parenthesis to tuple types printing

.github/workflows/main.yml, examples/.scripts/run-examples.sh
=> Replace globstar with find in run-examples script

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.5.5

doc/quint.md, quint/src/cli.ts
=> Add `--main` flag to `verify`

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.6.0

examples/solidity/GradualPonzi/gradualPonzi.qnt
Fix the run command in `gradualPonzi` (referred to `simplePonzi`)
=> Fix run command

doc/lang.md
Closes #706. Closes #530. I have made a pass over the manual and removed/fixed the outdated material. Not introducing `import ... from` yet, as it requires more careful rewriting. Postponed for #832.
=> clean the manual

quint/src/types/specialConstraints.ts
The way we construct and deconstruct records is interesting: in the
normal form we interpret a special set of operators such that
string-valued expressions given as arguments in our object language are
"lifted" into product type indexes in our meta language. E.g., in `label(r,
"foo")` we extract the value of the internal representation of the quint
string `"foo"` and use this as the label for projecting a value out of
the record `r`.
This lets us do some interesting (and perhaps undesirable?) things, like
construct labels which cannot be used to project out values using the
`r._` syntax sugar:
```
>>> Rec(":", 1)
{ :: 1 }
```
In the process of lifting the value of these strings into labels, we
also verify that each label supplied is in fact a string litteral:
E.g., …
=> Remove redundant type constraints on record label strings

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
- Better icons in VSCode outline view (#1024).
- VSCode plugin: Highlighting of identifiers that contain numbers (#1028)
=> VSCode Release v0.7.0

quint/src/flattening/flattener.ts, quint/src/flattening/instanceFlattener.ts, quint/src/ir/IRVisitor.ts, quint/test/flattening/instanceFlattener.test.ts
This introduces the instance flattener described in [ADR 07](https://github.com/informalsystems/quint/blob/main/doc/adr007-flattening.md). Closes #1101.
This is not connected to any code for the moment. My next PR will wire this in.
=> Instance flattener

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.8.0

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
- Added partial support for code completion and renaming (#1143)
=> VSCode Release v0.9.0

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.9.1

CHANGELOG.md, README.md, examples/language-features/option.qnt, quint/src/builtin.qnt
I added an update everywhere I could find that made sense to me and I knew how
to update. The outstanding work on this
https://github.com/informalsystems/quint/issues/1254.
Let me know if you can think of anything else that should be added to document
the feature at this point.
=> Document sum types

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.11.0

CHANGELOG.md, quint/io-cli-tests.md, quint/src/itf.ts, quint/test/itf.test.ts, quint/testFixture/_1054sumTypesInItf.qnt
=> Add support for variants in ITF

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.12.1

README.md
=> Add link to secret santa wiki article

doc/roadmap.md
Fixes some dead links in roadmap.md
=> doc: fix dead link in roadmap.md

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.13.0

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.13.1

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.13.2

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.13.7

README.md
As per suggestion from @ivan-gavran
=> Add notification about our co-design meetings to README

quint/src/quintVerifier.ts
=> Use Apalache versin 0.44.7

quint/src/apalache.ts
Just an Apalache version bump so the latest changes to type quantification are in place
=> Bump Apalache version

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.0

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.1

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.2

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.3

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.4

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.5

examples/spells/basicSpells.qnt, examples/spells/commonSpells.qnt
This adds a bunch of new spells I have written in the last months. Also includes the spells from #1440.
=> New spells

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
=> VSCode Release v0.14.6

docs/components/home/index.tsx
=> Fix minor typo: executuable -> executable

docs/pages/docs/development-docs/architecture-decision-records/adr001-transpiler-architecture.md, docs/pages/docs/development-docs/architecture-decision-records/adr005-type-system.md, docs/pages/docs/development-docs/architecture-decision-records/adr008-managing-apalache.md, docs/pages/docs/development-docs/rfcs/rfc007-foreign-calls.md, docs/pages/docs/language-basics.mdx, docs/pages/docs/quint.md, docs/roadmap.md, examples/.scripts/run-example.sh, examples/README.md, examples/classic/distributed/ConsensusAlgorithm/ConsensusAlg.qnt, examples/classic/distributed/ConsensusAlgorithm/KSetAgreementConsensus.qnt, quint/README.md, quint/src/cliCommands.ts, quint/src/itf.ts
=> Fixed the scenarios where agreement breaks with too many faults

examples/classic/distributed/ConsensusAlgorithm/ConsensusAlg.qnt, examples/classic/distributed/ConsensusAlgorithm/KSetAgreementConsensus.qnt
This fixes the comments and init definition to make it feasible to find violations in simulation.
=> Adjust params to enable finding violation on K set

docs/pages/docs/development-docs/rfcs/rfc001-sum-types.md, docs/pages/docs/development-docs/rfcs/rfc001-sum-types/rfc001-sum-types.org, docs/pages/docs/development-docs/rfcs/rfc001-sum-types/rfc001-sum-types.tex, quint/src/parsing/quintParserFrontend.ts
=> chore: fix some comments

quint/package-lock.json, quint/package.json, quint/src/cliCommands.ts, quint/src/quintRustWrapper.ts
=> Fetch Rust simulator from GitHub

.github/workflows/release-evaluator.yml
=> Fix checkout of repository when creating new evaluator release

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json, vscode/quint-vscode/server/yalc.lock
- Add new autocomplete options (#1616).
=> VSCode Release v0.15.0

.github/workflows/README.md, .github/workflows/benchmark.yml, .github/workflows/integration.yml, .github/workflows/lint-evaluator.yml, .github/workflows/lint-vscode.yml, .github/workflows/quint.yml, .github/workflows/release-evaluator.yml, .github/workflows/test-evaluator.yml, .github/workflows/vscode.yml
This is an attempt to fix the current problem on our CI where all checks are required, but not all of them are run in all PRs due to the new filters.
=> Use paths-filter for workflows

docs/pages/docs/lessons/booleans.md, docs/pages/docs/lessons/coin.md
Updates some broken links I found to working ones.
Should ref #1512
=> Fix broken links to working ones

.github/workflows/benchmark.yml, evaluator/src/lib.rs
=> Fix permissions on benchmark workflow

vscode/quint-vscode/CHANGELOG.md, vscode/quint-vscode/package-lock.json, vscode/quint-vscode/package.json, vscode/quint-vscode/server/package-lock.json, vscode/quint-vscode/server/package.json
- Fixed a critical issue on Windows where the server failed due to a problem creating the log file (#1672)
=> VSCode Release v0.15.1

.github/workflows/release.yml
=> fix: release binary script

evaluator/src/evaluator.rs, evaluator/src/value.rs, quint/src/effects/substitutions.ts
fix some minor issues in comments
=> chore: fix some minor issues in comments

docs/content/docs/checking-properties.mdx
=> My try on the intro to inductive invariants

quint/src/ir/IRprinting.ts
=> chore: remove redundant word

examples/cosmos/ics20/bank.qnt, examples/cosmos/ics20/denomTrace.qnt, examples/cosmos/ics20/ics20.qnt, examples/cosmos/lightclient/LCVerificationApi.qnt, examples/solidity/ERC20/erc20.qnt, examples/solidity/icse23-fig7/lottery.qnt
fix some minor issues for examples
=> chore: fix some minor issues for examples

docs/data/projects.ts
=> Added links for liquidity migration spec and neutron dex spec

docs/codetour/lesson4-sets/sets.qnt, docs/codetour/lesson4-sets/sets.template.qnt, docs/content/docs/lessons/sets.md, evaluator/fixtures/tictactoe.qnt, examples/games/tictactoe/tictactoe.qnt, examples/games/tictactoe/tictactoe.tla, examples/tutorials/sets.qnt, examples/verification/defaultOpNames.qnt, quint/src/effects/inferrer.ts
=> chore: fix some typos

docs/components/UpcomingTalk.tsx, docs/components/VideoEmbed.tsx, docs/components/home/code_sample.mdx, docs/components/home/index.tsx, docs/content/docs/_meta.tsx, docs/content/docs/lessons/_meta.json, docs/content/docs/lessons/_meta.ts, docs/content/docs/talks.mdx, docs/content/posts/alpenglow.mdx, docs/content/posts/inductive_invariants.mdx, docs/content/posts/secret_santa.mdx, docs/content/posts/soup.mdx
Fixes #1737 
This addresses some feedback I got on the website over the past couple of weeks. Commits explain each one.
Still pending feedback on the use-case hook.
=> [website] Small changes from several requests
